//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccDocSubSubSub
    {
        public int id { get; set; }
        public Nullable<int> IDFK { get; set; }
        public Nullable<double> AccID { get; set; }
        public Nullable<decimal> DebitVal { get; set; }
        public Nullable<decimal> CreditVal { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
    }
}
