//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccTree
    {
        public int AccID { get; set; }
        public string AccName { get; set; }
        public Nullable<int> Acckind { get; set; }
        public Nullable<double> ide { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> AccidFK { get; set; }
    }
}
