//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ag
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ag()
        {
            this.AgMove = new HashSet<AgMove>();
        }
    
        public int ID { get; set; }
        public int SysID { get; set; }
        public string AgntName { get; set; }
        public Nullable<int> LandNum { get; set; }
        public Nullable<int> FlatNum { get; set; }
        public Nullable<int> BuildNum { get; set; }
        public string StageNum { get; set; }
        public Nullable<decimal> DebF { get; set; }
        public Nullable<decimal> CreF { get; set; }
        public Nullable<decimal> DebCur { get; set; }
        public Nullable<decimal> CreCur { get; set; }
        public Nullable<decimal> DebTot { get; set; }
        public Nullable<decimal> CreTot { get; set; }
        public Nullable<decimal> DebLast { get; set; }
        public Nullable<decimal> CreLast { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
    
        public virtual SysList SysList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgMove> AgMove { get; set; }
    }
}
