//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentIDFind
    {
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> spacenum { get; set; }
        public Nullable<int> identity_num { get; set; }
        public string kind { get; set; }
    }
}
