//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class digtab
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int DigID { get; set; }
        public double DigMount { get; set; }
        public System.DateTime DigDate { get; set; }
        public string DigRemark { get; set; }
        public Nullable<int> UserIDCreated { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UserIDModif { get; set; }
        public Nullable<System.DateTime> ModifData { get; set; }
    
        public virtual AgentsList AgentsList { get; set; }
    }
}
