//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocAcc
    {
        public int ID { get; set; }
        public int DocID { get; set; }
        public Nullable<int> YearID { get; set; }
        public System.DateTime DocDate { get; set; }
        public int DocKind { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Remark { get; set; }
    }
}
