//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpDegree
    {
        public int ID { get; set; }
        public Nullable<int> Emp_ID { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string College { get; set; }
        public string University { get; set; }
        public string Remark { get; set; }
    
        public virtual DegreeList DegreeList { get; set; }
        public virtual HR_EmpReform HR_EmpReform { get; set; }
    }
}
