//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFamily
    {
        public int FmlySer { get; set; }
        public int Emp_id { get; set; }
        public int FmlyID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Remark { get; set; }
    }
}
