//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class emppunish
    {
        public int ID { get; set; }
        public Nullable<int> Emp_id { get; set; }
        public Nullable<int> DecisionNum { get; set; }
        public string DecisionKind { get; set; }
        public Nullable<System.DateTime> DecisionDate { get; set; }
        public Nullable<int> PunishID { get; set; }
        public Nullable<System.DateTime> PunishDate { get; set; }
        public Nullable<System.DateTime> UnPunishDate { get; set; }
        public Nullable<int> NoticeNum { get; set; }
        public Nullable<System.DateTime> NoticeDate { get; set; }
        public Nullable<decimal> DayNum { get; set; }
        public Nullable<decimal> PanishVal { get; set; }
    
        public virtual HR_EmpReform HR_EmpReform { get; set; }
        public virtual PunishList PunishList { get; set; }
    }
}
