//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpShft
    {
        public int ID { get; set; }
        public int Emp { get; set; }
        public string frm { get; set; }
        public string tw { get; set; }
        public Nullable<int> Dy { get; set; }
        public Nullable<int> Mo { get; set; }
        public Nullable<int> Yer { get; set; }
        public decimal Val { get; set; }
        public System.DateTime SDate { get; set; }
        public int Dept { get; set; }
    }
}
