//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpPro
    {
        public int ID { get; set; }
        public int ProListFK { get; set; }
        public int ExpNum { get; set; }
        public System.DateTime ExpDate { get; set; }
        public decimal ExpVal { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProList ProList { get; set; }
    }
}
