//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR_EmpReform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HR_EmpReform()
        {
            this.EmpDegree = new HashSet<EmpDegree>();
            this.EmpFin = new HashSet<EmpFin>();
            this.emploan = new HashSet<emploan>();
            this.emppunish = new HashSet<emppunish>();
            this.EmpVications = new HashSet<EmpVications>();
        }
    
        public int Emp_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Address { get; set; }
        public string Emp_NationalID { get; set; }
        public Nullable<int> SocialStatues { get; set; }
        public bool Gender { get; set; }
        public int Emp_kader_FK { get; set; }
        public int Emp_JCat_FK { get; set; }
        public Nullable<int> SpecificGrp { get; set; }
        public int Emp_JGrade { get; set; }
        public int Job_Status_ID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Emp_JTitile { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<bool> EmpIsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpDegree> EmpDegree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpFin> EmpFin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emploan> emploan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emppunish> emppunish { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpVications> EmpVications { get; set; }
        public virtual Hr_dept Hr_dept { get; set; }
        public virtual JobCategory JobCategory { get; set; }
        public virtual JobGarde JobGarde { get; set; }
        public virtual JobKader JobKader { get; set; }
        public virtual JobStatus JobStatus { get; set; }
    }
}
