//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jop
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public Nullable<decimal> MinSal { get; set; }
        public Nullable<decimal> MaxSal { get; set; }
        public System.DateTime CreatDate { get; set; }
        public int CreateBy { get; set; }
    }
}
