//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KPro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KPro()
        {
            this.ProList = new HashSet<ProList>();
        }
    
        public int ID { get; set; }
        public int TProFK { get; set; }
        public string KName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TPro TPro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProList> ProList { get; set; }
    }
}
