//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LevelList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LevelList()
        {
            this.AgentsList = new HashSet<AgentsList>();
        }
    
        public int LevelID { get; set; }
        public string LevelName { get; set; }
        public Nullable<System.DateTime> TosDate { get; set; }
        public Nullable<System.DateTime> PartDate { get; set; }
        public Nullable<int> PartNum { get; set; }
        public Nullable<int> PartMonth { get; set; }
        public Nullable<decimal> PartVal { get; set; }
        public Nullable<int> FreeMonth { get; set; }
        public bool IsActive { get; set; }
        public int SysID_FK { get; set; }
        public int BeginPart { get; set; }
        public Nullable<bool> Benfit { get; set; }
        public Nullable<int> BRatesFrom { get; set; }
        public Nullable<decimal> BRates { get; set; }
        public Nullable<bool> Punch { get; set; }
        public Nullable<int> PRatesFrom { get; set; }
        public Nullable<decimal> PRates { get; set; }
        public Nullable<bool> Fixe { get; set; }
        public Nullable<decimal> DebitVal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentsList> AgentsList { get; set; }
    }
}
