//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public decimal LoanMount { get; set; }
        public System.DateTime MonthPayed { get; set; }
        public int Months { get; set; }
        public int CutMonths { get; set; }
        public System.DateTime SCutMonths { get; set; }
        public int DeptID { get; set; }
        public string DocID { get; set; }
        public int EntID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
    }
}
