//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mval
    {
        public int SerID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> PartsID { get; set; }
        public Nullable<int> PartsNum { get; set; }
        public Nullable<decimal> Mount { get; set; }
        public Nullable<System.DateTime> MountDate { get; set; }
    }
}
