//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartMount
    {
        public int ID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public string AgentName { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<decimal> DepositPlus { get; set; }
        public Nullable<decimal> Mount { get; set; }
        public Nullable<decimal> Benefits { get; set; }
        public Nullable<decimal> Finedelay { get; set; }
        public Nullable<decimal> AccFinFund { get; set; }
        public Nullable<decimal> AccFundTrustees { get; set; }
        public Nullable<decimal> Expense { get; set; }
        public Nullable<System.DateTime> PartDate { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public int PartID_FK { get; set; }
        public Nullable<System.DateTime> UserDate { get; set; }
        public Nullable<int> ParID { get; set; }
    
        public virtual AgentsList AgentsList { get; set; }
        public virtual partsname partsname { get; set; }
    }
}
