//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectlist
    {
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TownID_FK { get; set; }
    }
}
