//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProList()
        {
            this.DurList = new HashSet<DurList>();
            this.ExpPro = new HashSet<ExpPro>();
            this.ArchPro = new HashSet<ArchPro>();
        }
    
        public int ID { get; set; }
        public string ProName { get; set; }
        public Nullable<int> ComFK { get; set; }
        public Nullable<int> KProFK { get; set; }
        public Nullable<int> PurNameFK { get; set; }
        public Nullable<System.DateTime> FirstAccepteDate { get; set; }
        public Nullable<System.DateTime> SecandAccepteDate { get; set; }
        public Nullable<System.DateTime> ThirdAceepteDate { get; set; }
        public Nullable<System.DateTime> DeclareDate { get; set; }
        public Nullable<System.DateTime> OpnTechDate { get; set; }
        public Nullable<System.DateTime> SetTechDate { get; set; }
        public Nullable<int> TechUser { get; set; }
        public Nullable<System.DateTime> TechDate { get; set; }
        public Nullable<System.DateTime> OpnFinDate { get; set; }
        public Nullable<System.DateTime> SetFinDate { get; set; }
        public Nullable<int> FinUser { get; set; }
        public Nullable<System.DateTime> FinDate { get; set; }
        public Nullable<int> ProNum { get; set; }
        public Nullable<System.DateTime> ProDate { get; set; }
        public Nullable<decimal> ProVal { get; set; }
        public Nullable<decimal> TotalVal { get; set; }
        public Nullable<System.DateTime> FixDate { get; set; }
        public Nullable<int> FixUser { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> FinalDate { get; set; }
        public Nullable<decimal> TargetVal { get; set; }
        public Nullable<decimal> TargetValTime { get; set; }
        public Nullable<decimal> TargetPrec { get; set; }
        public Nullable<decimal> ExpForNow { get; set; }
        public Nullable<decimal> TargetFin { get; set; }
        public Nullable<int> ProSt { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public Nullable<int> Posted { get; set; }
        public Nullable<bool> ProStop { get; set; }
        public Nullable<System.DateTime> StopDate { get; set; }
        public Nullable<System.DateTime> DurDateFirst { get; set; }
        public Nullable<System.DateTime> DurDateSec { get; set; }
        public Nullable<System.DateTime> DurDateThird { get; set; }
        public Nullable<System.DateTime> OverFirst { get; set; }
        public Nullable<System.DateTime> OverSec { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DurList> DurList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpPro> ExpPro { get; set; }
        public virtual KPro KPro { get; set; }
        public virtual PostList PostList { get; set; }
        public virtual PurType PurType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArchPro> ArchPro { get; set; }
    }
}
