//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProState
    {
        public int ID { get; set; }
        public string ProName { get; set; }
        public string PostedName { get; set; }
        public Nullable<decimal> ExpVal { get; set; }
    }
}
