//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sal
    {
        public int ID { get; set; }
        public int EmpID { get; set; }
        public int Mon { get; set; }
        public int Yer { get; set; }
        public decimal Lon { get; set; }
        public decimal Pun { get; set; }
        public decimal Vac { get; set; }
        public decimal CtAll { get; set; }
        public decimal MainSal { get; set; }
        public decimal Mor { get; set; }
        public decimal AdAll { get; set; }
        public decimal NetSall { get; set; }
        public bool Status { get; set; }
        public string PdDoc { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
