//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialBalance
    {
        public int AccID { get; set; }
        public string AccName { get; set; }
        public Nullable<int> AccKind { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> AccidFK { get; set; }
        public Nullable<int> ADebit { get; set; }
        public Nullable<int> ACredit { get; set; }
        public Nullable<int> BDebit { get; set; }
        public Nullable<int> BCredit { get; set; }
        public Nullable<int> CDebit { get; set; }
        public Nullable<int> CCredit { get; set; }
    }
}
