//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEDJ
    {
        public int ID { get; set; }
        public string EmpName { get; set; }
        public string jop { get; set; }
        public string Dept { get; set; }
        public int JopID { get; set; }
        public int DeptID { get; set; }
        public int CcID { get; set; }
        public string CcName { get; set; }
    }
}
