//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmpl
    {
        public int ID { get; set; }
        public string Jop { get; set; }
        public string Dept { get; set; }
        public string FullName { get; set; }
        public System.DateTime HireDate { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string NatID { get; set; }
        public string CcName { get; set; }
        public bool Shift { get; set; }
    }
}
