//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEmplon
    {
        public int ID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> JopID { get; set; }
        public string FullName { get; set; }
        public string dept { get; set; }
        public string jop { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> NetSall { get; set; }
    }
}
