//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLoanE
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public decimal LoanMount { get; set; }
        public System.DateTime MonthPayed { get; set; }
        public string DocID { get; set; }
        public int EntID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public string Name { get; set; }
        public System.DateTime SCutMonths { get; set; }
    }
}
