//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalEntry
    {
        public int DeptID { get; set; }
        public string Dept { get; set; }
        public int Mon { get; set; }
        public int Yer { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Pun { get; set; }
        public Nullable<decimal> Vac { get; set; }
        public Nullable<decimal> CtAll { get; set; }
        public Nullable<decimal> MainSal { get; set; }
        public Nullable<decimal> Mor { get; set; }
        public Nullable<decimal> AdAll { get; set; }
        public Nullable<decimal> NetSall { get; set; }
        public bool Status { get; set; }
        public int CcID { get; set; }
        public string CcName { get; set; }
    }
}
