//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSalary
    {
        public Nullable<int> ID { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> JopID { get; set; }
        public string FullName { get; set; }
        public string Dept { get; set; }
        public string Jop { get; set; }
        public Nullable<decimal> Lon { get; set; }
        public Nullable<decimal> Pun { get; set; }
        public Nullable<decimal> Vac { get; set; }
        public Nullable<decimal> CtAll { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Mor { get; set; }
        public Nullable<decimal> AdAll { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Mon { get; set; }
        public Nullable<int> Yer { get; set; }
        public Nullable<decimal> NetSall { get; set; }
    }
}
