//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vURoles
    {
        public int RoleID { get; set; }
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public string UserName { get; set; }
        public int UsrRolID { get; set; }
        public int UsrID { get; set; }
        public int UserID { get; set; }
        public string EntryKey { get; set; }
        public string FullName { get; set; }
    }
}
