//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vVacE
    {
        public int EmpID { get; set; }
        public string FullName { get; set; }
        public int DeptID { get; set; }
        public string Name { get; set; }
        public int ID { get; set; }
        public System.DateTime VacStrt { get; set; }
        public System.DateTime VacEnd { get; set; }
        public decimal VMount { get; set; }
        public int Ds { get; set; }
        public bool Cuts { get; set; }
        public System.DateTime CreatDate { get; set; }
        public System.DateTime CutMonth { get; set; }
        public string Nots { get; set; }
        public string OrderBy { get; set; }
    }
}
