//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class YearsList1
    {
        public int ID { get; set; }
        public string YearsNames { get; set; }
        public System.DateTime STDate { get; set; }
        public System.DateTime EnDate { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreaateDate { get; set; }
        public int CreateBy { get; set; }
    }
}
